version: "2"

plugins:
  checkstyle:
    enabled: true

  pmd:
    enabled: true

  radon:
    enabled: true

  flog:
    enabled: true

  reek:
    enabled: true

  sonar-java:
    enabled: true

  sonar-pyhton:
    enabled: true

exclude_patterns:
    - "config/"
    - "db/"
    - "dist/"
    - "features/"
    - "**/node_modules/"
    - "script/"
    - "**/spec/"
    - "**/test/"
    - "**/tests/"
    - "Tests/"
    - "**/vendor/"
    - "**/*_test.go"
    - "**/*.d.ts"
    - "third_party/"